import { defineSpec, file, listParams, paginated, ref, resource, type EndpointDef, type ParamDef } from '@/openapi/dsl';
import { PLANS, TENANT_STATUSES } from '@/lib/domain';
import { TENANT_SEGMENTS } from './types';

const id: Record<string, ParamDef> = { id: { type: 'string', description: 'Tenant id, e.g. `tn_amplify`.' } };
const example = { params: { id: 'tn_amplify' } };
const directoryFilters: Record<string, ParamDef> = {
  segment: { type: 'string', enum: TENANT_SEGMENTS },
  plan: { type: 'string', enum: PLANS },
  status: { type: 'string', enum: TENANT_STATUSES },
};

/** POST /tenants/{id}/{action} — single-purpose actions returning the updated tenant. */
const action = (
  path: string,
  summary: string,
  auth: EndpointDef['auth'],
  audit: EndpointDef['audit'],
  extra: Partial<EndpointDef> = {},
): EndpointDef => ({
  method: 'POST',
  path: `/tenants/{id}/${path}`,
  summary,
  auth,
  path_params: id,
  response: resource(ref('TenantDetail')),
  ...(audit ? { audit } : {}),
  example,
  ...extra,
});

export const spec = defineSpec({
  tag: 'Tenants',
  description: 'Tenant directory, provisioning and per-tenant administration.',
  endpoints: [
    {
      method: 'GET',
      path: '/tenants',
      summary: 'List tenants',
      auth: 'tenants.view',
      query: { ...listParams(['name', 'students', 'mrr', 'created_at', 'last_active_at']), ...directoryFilters },
      response: paginated(ref('Tenant')),
      example: { query: { per_page: 5, sort: '-mrr' } },
    },
    {
      method: 'GET',
      path: '/tenants/summary',
      summary: 'Directory KPIs and segment counts',
      auth: 'tenants.view',
      response: resource(ref('TenantSummary')),
    },
    {
      method: 'GET',
      path: '/tenants/export',
      summary: 'Export the filtered directory as CSV',
      auth: 'tenants.view',
      query: { search: { type: 'string' }, ...directoryFilters },
      response: file('text/csv', 'tenants.csv'),
      audit: { text: 'Exported {n} tenants to CSV', category: 'Tenants' },
    },
    {
      method: 'POST',
      path: '/tenants',
      summary: 'Provision a tenant',
      description:
        'Creates the workspace on `{slug}.{primary_domain}` in Trial for the platform trial length and emails the owner an invite.',
      auth: 'tenants.manage',
      body: ref('ProvisionTenantInput'),
      response: resource(ref('Tenant'), 201),
      audit: { text: 'Provisioned tenant "{name}" on {plan}', category: 'Tenants' },
      example: { body: { name: 'Harbor Music School', owner_email: 'ana@harbor.com', plan: 'Growth' } },
    },
    {
      method: 'POST',
      path: '/tenants/bulk',
      summary: 'Bulk action on tenants',
      auth: 'tenants.view',
      description: '`suspend` requires `tenants.suspend`.',
      body: {
        type: 'object',
        required: ['action', 'ids'],
        properties: { action: { type: 'string', enum: ['suspend', 'watch', 'export'] }, ids: { type: 'array', items: { type: 'string' } } },
      },
      response: resource({ type: 'object', required: ['affected'], properties: { affected: { type: 'integer' } } }),
      example: { body: { action: 'watch', ids: ['tn_amplify'] } },
    },
    {
      method: 'POST',
      path: '/tenants/email',
      summary: 'Email tenant owners',
      description: 'Merge tags: `{owner_name}`, `{tenant_name}`, `{plan}`.',
      auth: 'tenants.manage',
      body: {
        type: 'object',
        required: ['ids', 'subject', 'body'],
        properties: {
          ids: { type: 'array', items: { type: 'string' } },
          subject: { type: 'string', maxLength: 150 },
          body: { type: 'string' },
        },
      },
      response: resource({ type: 'object', required: ['sent'], properties: { sent: { type: 'integer' } } }),
      audit: { text: 'Emailed {n} tenant owners: "{subject}"', category: 'Tenants' },
      example: { body: { ids: ['tn_amplify'], subject: 'Hello', body: 'Hi {owner_name}' } },
    },
    {
      method: 'GET',
      path: '/tenants/{id}',
      summary: 'Tenant detail',
      auth: 'tenants.view',
      path_params: id,
      response: resource(ref('TenantDetail')),
      example,
    },
    {
      method: 'PATCH',
      path: '/tenants/{id}',
      summary: 'Update plan, data residency or internal note',
      auth: 'tenants.manage',
      path_params: id,
      body: ref('TenantUpdate'),
      response: resource(ref('TenantDetail')),
      audit: { text: 'Moved {name} from {a} to {b} (plan) · Scheduled data-residency move … (region, Security)', category: 'Tenants' },
      example: { ...example, body: { plan: 'Scale' } },
    },
    {
      method: 'PUT',
      path: '/tenants/{id}/limits',
      summary: 'Override limits (0 = unlimited, null = plan default)',
      auth: 'tenants.manage',
      path_params: id,
      body: {
        type: 'object',
        required: ['limits'],
        properties: {
          limits: {
            type: 'object',
            additionalProperties: { type: ['integer', 'null'], minimum: 0 },
            description: 'Keys: storage_gb, staff_seats, api_per_minute, students, courses, live_room_minutes.',
          },
        },
      },
      response: resource(ref('TenantDetail')),
      audit: { text: 'Updated limits for {name}', category: 'Tenants' },
      example: { ...example, body: { limits: { staff_seats: 12 } } },
    },
    {
      method: 'PUT',
      path: '/tenants/{id}/modules/{module}',
      summary: 'Grant or revoke a module (null = plan default)',
      auth: 'tenants.manage',
      path_params: { ...id, module: { type: 'string', description: 'Tenant module id, e.g. `aistudio`.' } },
      body: { type: 'object', required: ['enabled'], properties: { enabled: { type: ['boolean', 'null'] } } },
      response: resource(ref('TenantDetail')),
      audit: { text: 'Granted/Revoked {module} for {name}', category: 'Tenants' },
      example: { params: { id: 'tn_amplify', module: 'aistudio' }, body: { enabled: true } },
    },
    {
      method: 'DELETE',
      path: '/tenants/{id}/modules',
      summary: 'Reset module access to the plan',
      auth: 'tenants.manage',
      path_params: id,
      response: resource(ref('TenantDetail')),
      audit: { text: 'Reset module access for {name} to the {plan} plan', category: 'Tenants' },
      example,
    },
    {
      method: 'PUT',
      path: '/tenants/{id}/flags/{key}',
      summary: 'Override a feature flag for this tenant',
      auth: 'flags.manage',
      path_params: { ...id, key: { type: 'string' } },
      body: { type: 'object', required: ['enabled'], properties: { enabled: { type: 'boolean' } } },
      response: resource(ref('TenantDetail')),
      audit: { text: 'Enabled/Disabled "{flag}" for {name}', category: 'Flags' },
      example: { params: { id: 'tn_amplify', key: 'ai_outline' }, body: { enabled: false } },
    },
    {
      method: 'POST',
      path: '/tenants/{id}/extensions/{key}/comp',
      summary: 'Comp an extension (free until revoked)',
      auth: 'billing.manage',
      path_params: { ...id, key: { type: 'string' } },
      response: resource(ref('TenantDetail')),
      audit: { text: 'Comped {extension} for {name}', category: 'Billing' },
      example: { params: { id: 'tn_amplify', key: 'ai' } },
    },
    {
      method: 'DELETE',
      path: '/tenants/{id}/extensions/{key}/comp',
      summary: 'Revoke an extension comp',
      auth: 'billing.manage',
      path_params: { ...id, key: { type: 'string' } },
      response: resource(ref('TenantDetail')),
      audit: { text: 'Revoked {extension} comp for {name}', category: 'Billing' },
      example: { params: { id: 'tn_amplify', key: 'ai' } },
    },
    {
      method: 'POST',
      path: '/tenants/{id}/watch',
      summary: 'Watch tenant (per staff user)',
      auth: 'tenants.view',
      path_params: id,
      response: resource(ref('TenantDetail')),
      example,
    },
    {
      method: 'DELETE',
      path: '/tenants/{id}/watch',
      summary: 'Stop watching tenant',
      auth: 'tenants.view',
      path_params: id,
      response: resource(ref('TenantDetail')),
      example,
    },
    action(
      'transfer-ownership',
      'Start an ownership transfer',
      'tenants.manage',
      { text: 'Started ownership transfer of {name} to {email}', category: 'Security' },
      {
        body: { type: 'object', required: ['email'], properties: { email: { type: 'string', format: 'email' } } },
        example: { ...example, body: { email: 'new.owner@amplify.com' } },
      },
    ),
    {
      method: 'POST',
      path: '/tenants/{id}/impersonate',
      summary: 'Start a read-only impersonation session',
      auth: 'tenants.impersonate',
      path_params: id,
      response: resource(ref('Impersonation')),
      audit: { text: 'Signed in as owner of {name} (read-only)', category: 'Security' },
      example,
    },
    action('suspend', 'Suspend tenant', 'tenants.suspend', { text: 'Suspended {name}', category: 'Tenants' }, { errors: [422] }),
    action('reactivate', 'Reactivate tenant', 'tenants.suspend', { text: 'Reactivated {name}', category: 'Tenants' }),
    action(
      'extend-trial',
      'Extend trial by 14 days',
      'tenants.manage',
      { text: "Extended {name}'s trial by 14 days", category: 'Tenants' },
      { errors: [422], example: { params: { id: 'tn_ledger' } } },
    ),
    action('export', 'Queue a full data export', 'tenants.manage', { text: 'Queued full data export for {name}', category: 'Security' }),
    action('purge', 'Schedule a data purge (30-day grace)', 'tenants.purge', {
      text: 'Scheduled data purge for {name} (30-day grace period)',
      category: 'Security',
    }),
    action('revoke-sessions', 'Revoke all sessions', 'tenants.manage', { text: 'Revoked all sessions for {name}', category: 'Security' }),
    action('reset-password', 'Send the owner a password reset', 'tenants.manage', {
      text: 'Sent password reset to the owner of {name}',
      category: 'Security',
    }),
    action('reissue-ssl', 'Reissue the SSL certificate', 'tenants.manage', {
      text: 'Reissued SSL certificate for {domain}',
      category: 'Security',
    }),
  ],
});
