import { defineSpec, ref, resource, type ParamDef } from '@/openapi/dsl';

const tenantId: Record<string, ParamDef> = {
  id: { type: 'string', description: 'Tenant id (must have AI studio usage), e.g. `tn_amplify`.' },
};
const experimentId: Record<string, ParamDef> = { id: { type: 'string', description: 'Experiment id, e.g. `ex_site_builder`.' } };

export const spec = defineSpec({
  tag: 'Analytics',
  description: 'Growth, usage, system health, AI cost and experiment analytics. Tenant figures are derived from the tenant table.',
  endpoints: [
    {
      method: 'GET',
      path: '/analytics/growth',
      summary: 'Growth funnel, cohorts, health scores and onboarding',
      auth: 'analytics.view',
      response: resource(ref('Growth')),
    },
    {
      method: 'GET',
      path: '/analytics/usage',
      summary: 'Metered usage vs capacity and top consumers',
      auth: 'analytics.view',
      response: resource(ref('Usage')),
    },
    {
      method: 'GET',
      path: '/analytics/health',
      summary: 'Service status, job queues and email deliverability',
      auth: 'analytics.view',
      response: resource(ref('Health')),
    },
    {
      method: 'POST',
      path: '/analytics/health/queues/{queue}/retry',
      summary: 'Requeue failed jobs on a queue',
      auth: 'platform.manage',
      path_params: { queue: { type: 'string', description: 'Queue name, e.g. `emails`.' } },
      response: resource(ref('QueueRetryResult')),
      errors: [404, 422],
      audit: { text: 'Requeued {n} failed jobs on the {queue} queue', category: 'Flags' },
      example: { params: { queue: 'emails' } },
    },
    {
      method: 'GET',
      path: '/analytics/ai',
      summary: 'AI usage, cost, margin and routing settings',
      auth: 'analytics.view',
      response: resource(ref('AiUsage')),
    },
    {
      method: 'PUT',
      path: '/analytics/ai/settings',
      summary: 'Update the AI monthly cost cap and/or model routing policy',
      description: 'Send at least one field. `monthly_cap` is whole dollars between 100 and 100,000.',
      auth: 'billing.manage',
      body: ref('AiSettingsInput'),
      response: resource(ref('AiUsage')),
      audit: { text: 'Set the AI monthly cost cap to ${cap} · Changed AI model routing to {policy}', category: 'Billing' },
      example: { body: { monthly_cap: 3000, routing_policy: 'balanced' } },
    },
    {
      method: 'POST',
      path: '/analytics/ai/tenants/{id}/throttle',
      summary: 'Throttle a tenant to the low-cost AI model',
      auth: 'billing.manage',
      path_params: tenantId,
      response: resource(ref('AiUsage')),
      errors: [404],
      audit: { text: 'Throttled {name} to the low-cost AI model', category: 'Billing' },
      example: { params: { id: 'tn_amplify' } },
    },
    {
      method: 'DELETE',
      path: '/analytics/ai/tenants/{id}/throttle',
      summary: 'Restore full AI speed for a tenant',
      auth: 'billing.manage',
      path_params: tenantId,
      response: resource(ref('AiUsage')),
      errors: [404],
      audit: { text: 'Restored full AI speed for {name}', category: 'Billing' },
      example: { params: { id: 'tn_amplify' } },
    },
    {
      method: 'GET',
      path: '/analytics/experiments',
      summary: 'Experiments with lift, confidence and verdict',
      auth: 'analytics.view',
      response: resource(ref('Experiments')),
    },
    {
      method: 'POST',
      path: '/analytics/experiments/{id}/promote',
      summary: 'Promote a running experiment to 100% (enables its flag for all tenants)',
      auth: 'platform.manage',
      path_params: experimentId,
      response: resource(ref('Experiments')),
      errors: [404, 422],
      audit: { text: 'Promoted experiment "{name}" to 100%', category: 'Flags' },
      example: { params: { id: 'ex_site_builder' } },
    },
    {
      method: 'POST',
      path: '/analytics/experiments/{id}/stop',
      summary: 'Stop a running experiment (traffic returns to control)',
      auth: 'platform.manage',
      path_params: experimentId,
      response: resource(ref('Experiments')),
      errors: [404, 422],
      audit: { text: 'Stopped experiment "{name}" — traffic returned to control', category: 'Flags' },
      example: { params: { id: 'ex_ai_outline' } },
    },
  ],
});
