import { defineSpec, paginated, ref, resource, type ParamDef } from '@/openapi/dsl';

const page: Record<string, ParamDef> = {
  page: { type: 'integer', description: 'Page number (1-based).' },
  per_page: { type: 'integer', description: 'Items per page (max 100, default 25).' },
};
const restoreId: Record<string, ParamDef> = { id: { type: 'string', description: 'Restore id, e.g. `rs_…`.' } };

export const spec = defineSpec({
  tag: 'Backup',
  description:
    'Platform backups, point-in-time recovery, two-person restores, backup policy and per-tenant data exports. Restores move `staged` → `approved` → `running` → `completed` (or `staged` → `cancelled`) on the server.',
  endpoints: [
    {
      method: 'GET',
      path: '/backup',
      summary: 'Backup health summary and destinations',
      auth: 'platform.view',
      response: resource(ref('BackupSummary')),
    },
    {
      method: 'GET',
      path: '/backup/points',
      summary: 'Restore points, newest first',
      auth: 'platform.view',
      query: page,
      response: paginated(ref('BackupPoint')),
      example: { query: { per_page: 20 } },
    },
    {
      method: 'POST',
      path: '/backup/run',
      summary: 'Take a manual snapshot of every tenant database',
      auth: 'platform.manage',
      body: {
        type: 'object',
        properties: { label: { type: ['string', 'null'], maxLength: 80, description: 'Operator note, e.g. "before pricing migration".' } },
      },
      response: resource(ref('BackupPoint'), 201),
      audit: { text: 'Started a manual platform backup', category: 'Security' },
      example: { body: { label: 'before pricing migration' } },
    },
    {
      method: 'POST',
      path: '/backup/drills',
      summary: 'Run a restore drill (sandbox restore of a tenant)',
      auth: 'platform.manage',
      response: resource(ref('BackupSummary')),
      audit: { text: 'Ran a restore drill (sandbox restore of {tenant})', category: 'Security' },
      example: {},
    },
    {
      method: 'GET',
      path: '/backup/restores',
      summary: 'Restores, most recently staged first',
      auth: 'platform.view',
      query: page,
      response: paginated(ref('Restore')),
    },
    {
      method: 'POST',
      path: '/backup/restores',
      summary: 'Stage a restore (needs a second staff member to approve)',
      description:
        'Give either `point_id` or `pitr_date` + `pitr_time` (point-in-time recovery within the WAL window, replayed from the nearest snapshot before the target). Only one restore may be staged, approved or running at a time (422 `restore`).',
      auth: 'platform.manage',
      body: ref('StageRestoreInput'),
      response: resource(ref('Restore'), 201),
      audit: { text: 'Staged {dry-run|live} restore of {scope} ← {source}', category: 'Security' },
      example: { body: { point_id: 'bp_4', scope: 'tenant', tenant_id: 'tn_amplify', dry_run: true } },
    },
    {
      method: 'POST',
      path: '/backup/restores/{id}/approve',
      summary: 'Approve a staged restore and queue it',
      description: 'The staff member who staged the restore can never approve it (403). 422 when the restore is no longer staged.',
      auth: 'platform.manage',
      path_params: restoreId,
      response: resource(ref('Restore')),
      errors: [404, 422],
      audit: { text: 'Approved {dry-run|live} restore of {scope} ← {source}', category: 'Security' },
      example: { skip: 'Needs a restore staged by a different staff member; the seed has no restores.' },
    },
    {
      method: 'POST',
      path: '/backup/restores/{id}/cancel',
      summary: 'Cancel a staged restore',
      auth: 'platform.manage',
      path_params: restoreId,
      response: resource(ref('Restore')),
      errors: [404, 422],
      audit: { text: 'Cancelled staged restore of {scope} ← {source}', category: 'Security' },
      example: { skip: 'Needs a staged restore; the seed has no restores and their ids are generated.' },
    },
    { method: 'GET', path: '/backup/settings', summary: 'Backup policy', auth: 'platform.view', response: resource(ref('BackupSettings')) },
    {
      method: 'PATCH',
      path: '/backup/settings',
      summary: 'Update the backup policy',
      auth: 'platform.manage',
      body: ref('BackupSettingsUpdate'),
      response: resource(ref('BackupSettings')),
      audit: {
        text: 'Updated backup policy: {changes} · Enabled/Disabled backup immutability lock (WORM) · Enabled/Disabled cross-region backup replication',
        category: 'Security',
      },
      example: { body: { retention_days: 45, nightly_window: '02:30' } },
    },
    {
      method: 'GET',
      path: '/backup/exports',
      summary: 'Per-tenant data exports, newest first',
      auth: 'platform.view',
      query: page,
      response: paginated(ref('TenantExport')),
    },
    {
      method: 'POST',
      path: '/backup/exports',
      summary: 'Queue a per-tenant data export (download link valid 7 days)',
      auth: 'platform.manage',
      body: ref('TenantExportInput'),
      response: resource(ref('TenantExport'), 201),
      audit: { text: 'Queued {format} data export for {tenant}', category: 'Security' },
      example: { body: { tenant_id: 'tn_amplify', format: 'json', include_media: true } },
    },
    {
      method: 'GET',
      path: '/backup/activity',
      summary: 'Backup activity feed, newest first',
      auth: 'platform.view',
      query: page,
      response: paginated(ref('BackupActivity')),
      example: { query: { per_page: 8 } },
    },
  ],
});
